import { TelemetryEvent } from '../types';

export const DEMO_EVENTS: TelemetryEvent[] = [
  {
    eventId: 'EVT-DEMO-001',
    busId: 'BUS-PUNE-101',
    eventType: 'POTHOLE',
    detectionStatus: 'POTHOLE_DETECTED',
    confidence: 0.94,
    latitude: 18.5204,
    longitude: 73.8567,
    gpsFixStatus: '3D_FIX',
    timestamp: new Date().toISOString(),
    boundingBox: '[120, 180, 260, 310]',
    severity: 'CRITICAL',
    source: 'pune_bus_route_4.mp4',
    metadata: '{"estimated_area_sqm": 0.65, "is_demo": true}',
    lifecycleStatus: 'VERIFIED',
    observationCount: 3,
    createdAt: new Date().toISOString(),
  },
  {
    eventId: 'EVT-DEMO-002',
    busId: 'BUS-PUNE-104',
    eventType: 'TRAFFIC_SIGNAL',
    detectionStatus: 'SIGNAL_POSSIBLE_MALFUNCTION',
    confidence: 0.89,
    latitude: 18.5312,
    longitude: 73.8445,
    gpsFixStatus: '3D_FIX',
    timestamp: new Date().toISOString(),
    boundingBox: '[300, 150, 360, 320]',
    severity: 'CRITICAL',
    source: 'pune_bus_route_12.mp4',
    metadata: '{"status": "SIGNAL_POSSIBLE_MALFUNCTION", "signal_state": "OFF", "observation_duration_seconds": 22.5, "is_demo": true}',
    lifecycleStatus: 'DETECTED',
    observationCount: 12,
    createdAt: new Date().toISOString(),
  },
  {
    eventId: 'EVT-DEMO-003',
    busId: 'BUS-PUNE-108',
    eventType: 'TRAFFIC_DENSITY',
    detectionStatus: 'HIGH',
    confidence: 0.85,
    latitude: 18.5155,
    longitude: 73.8512,
    gpsFixStatus: '3D_FIX',
    timestamp: new Date().toISOString(),
    boundingBox: null,
    severity: 'HIGH',
    source: 'pune_bus_route_8.mp4',
    metadata: '{"density_level": "HIGH", "total_vehicles_detected": 14, "is_demo": true}',
    lifecycleStatus: 'DETECTED',
    observationCount: 1,
    createdAt: new Date().toISOString(),
  },
  {
    eventId: 'EVT-DEMO-004',
    busId: 'BUS-PUNE-102',
    eventType: 'ZEBRA_CROSSING',
    detectionStatus: 'MISSING',
    confidence: 0.0,
    latitude: 18.5280,
    longitude: 73.8620,
    gpsFixStatus: '3D_FIX',
    timestamp: new Date().toISOString(),
    boundingBox: null,
    severity: 'HIGH',
    source: 'pune_bus_route_2.mp4',
    metadata: '{"status": "UNKNOWN", "implementation_status": "PROTOTYPE", "is_demo": true}',
    lifecycleStatus: 'ASSIGNED',
    observationCount: 2,
    createdAt: new Date().toISOString(),
  },
  {
    eventId: 'EVT-DEMO-005',
    busId: 'BUS-PUNE-105',
    eventType: 'TRAFFIC_SIGNAL',
    detectionStatus: 'SIGNAL_OPERATING',
    confidence: 0.95,
    latitude: 18.5089,
    longitude: 73.8321,
    gpsFixStatus: '3D_FIX',
    timestamp: new Date().toISOString(),
    boundingBox: '[250, 120, 310, 290]',
    severity: 'INFO',
    source: 'pune_bus_route_5.mp4',
    metadata: '{"status": "SIGNAL_OPERATING", "signal_state": "GREEN", "is_demo": true}',
    lifecycleStatus: 'DETECTED',
    observationCount: 8,
    createdAt: new Date().toISOString(),
  },
  {
    eventId: 'EVT-DEMO-006',
    busId: 'BUS-PUNE-101',
    eventType: 'POTHOLE',
    detectionStatus: 'POTHOLE_DETECTED',
    confidence: 0.76,
    latitude: 18.5401,
    longitude: 73.8290,
    gpsFixStatus: '3D_FIX',
    timestamp: new Date().toISOString(),
    boundingBox: '[80, 140, 180, 240]',
    severity: 'MEDIUM',
    source: 'pune_bus_route_1.mp4',
    metadata: '{"estimated_area_sqm": 0.28, "is_demo": true}',
    lifecycleStatus: 'RESOLVED',
    observationCount: 1,
    createdAt: new Date().toISOString(),
  }
];
